# Generated by Django 2.0.1 on 2018-05-05 20:08

from django.db import migrations, models
import django_pki.common.elliptic_curve
import django_pki.common.encoding
import django_pki.common.encryption_schema
import django_pki.common.private_format
import django_pki.common.private_key_size
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Encryption Schema', enumfields.fields.EnumField(enum=django_pki.common.encryption_schema.EncryptionSchema, max_length=1)),
                ('Private Key Size', enumfields.fields.EnumField(enum=django_pki.common.private_key_size.PrivateKeySize, max_length=1, null=True)),
                ('Elliptic Curve', enumfields.fields.EnumField(enum=django_pki.common.elliptic_curve.EllipticCurve, max_length=1, null=True)),
                ('Encoding', enumfields.fields.EnumField(enum=django_pki.common.encoding.Encoding, max_length=1)),
                ('Private Format', enumfields.fields.EnumField(enum=django_pki.common.private_format.PrivateFormat, max_length=1)),
                ('Passphrase', models.CharField(max_length=256, null=True)),
                ('_key_bytes', models.TextField()),
            ],
        ),
    ]
